import { z } from "zod";

/**
 * A single item in a study plan — either a topic or problem to complete.
 */
export const StudyPlanItemSchema = z.object({
  id: z.string(),
  type: z.enum(["topic", "problem"]),
  /** Display title for the item. */
  title: z.string(),
  /** Whether this item has been completed in the plan. */
  completed: z.boolean(),
  /** Optional notes about why this item is in the plan. */
  reason: z.string().optional(),
  /** Estimated time in minutes. */
  estimatedMinutes: z.number().optional(),
  /** Priority within the plan. */
  priority: z.enum(["high", "medium", "low"]).optional(),
});

export type StudyPlanItem = z.infer<typeof StudyPlanItemSchema>;

/**
 * A persisted study plan generated by AI or created manually.
 * Stored in ~/knowledge-workspace/.config/study-plans/{id}.json
 */
export const StudyPlanSchema = z.object({
  id: z.string(),
  title: z.string(),
  /** Optional description of the plan's goals. */
  description: z.string().optional(),
  /** Category focus, or null for comprehensive plans. */
  category: z.string().nullable().optional(),
  /** Target timeline in weeks. */
  timelineWeeks: z.number().optional(),
  /** Ordered list of items to complete. */
  items: z.array(StudyPlanItemSchema),
  /** AI-generated markdown content with full plan details. */
  content: z.string(),
  /** Whether the plan is currently active. */
  active: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type StudyPlan = z.infer<typeof StudyPlanSchema>;
